import {
    create,
    evaluateDependencies,
    unitDependencies,
    complexDependencies,
    derivativeDependencies,
    meanDependencies,
    stdDependencies,
    varianceDependencies,
    medianDependencies,
    detDependencies,
    invDependencies,
    transposeDependencies,
    matrixDependencies,
    addDependencies,
    subtractDependencies,
    multiplyDependencies,
    divideDependencies,
    absDependencies,
    sinDependencies,
    cosDependencies,
    tanDependencies,
    logDependencies,
    log10Dependencies,
    powDependencies,
    sqrtDependencies,
    factorialDependencies,
    expDependencies,
} from 'mathjs';

const math = create({
    evaluateDependencies,
    unitDependencies,
    complexDependencies,
    derivativeDependencies,
    meanDependencies,
    stdDependencies,
    varianceDependencies,
    medianDependencies,
    detDependencies,
    invDependencies,
    transposeDependencies,
    matrixDependencies,
    addDependencies,
    subtractDependencies,
    multiplyDependencies,
    divideDependencies,
    absDependencies,
    sinDependencies,
    cosDependencies,
    tanDependencies,
    logDependencies,
    log10Dependencies,
    powDependencies,
    sqrtDependencies,
    factorialDependencies,
    expDependencies,
});

export const {
    evaluate,
    unit,
    complex,
    derivative,
    mean,
    std,
    variance,
    median,
    det,
    inv,
    transpose,
    matrix,
    add,
    subtract,
    multiply,
    divide,
    abs
} = math;

export default math;
